---
# Ink low notification.
#
id: 66110a38-a718-44ac-aa23-62307edb388d
alias: Corridoio Ink Low Notification
trigger:
  - platform: time
    at: '09:30:00'
condition:
  - condition: numeric_state
    entity_id:
      - sensor.corridoio_stampante_black_ink
      - sensor.corridoio_stampante_cyan_ink
      - sensor.corridoio_stampante_magenta_ink
      - sensor.corridoio_stampante_yellow_ink
    below: 15
action:
  - service: script.sistema_text_and_announce
    data_template:
      message: >
        Controllare le cartucce della stampante.
        {% set inklist = (expand("group.areas_corridoio_stampante_ink") | selectattr('state', 'lessthan', '16') | list) %}

        {% set letter = "a" if inklist | count == 1 else "e" %}

        L{{ letter }} cartucc{{ "i" if letter == "a" }}{{ letter }}: {{ inklist | map(attribute="name") | join(', ') }} ha{{ "nno" if letter == "e" }} bisogno di essere cambiat{{ letter }}.
