- hosts: hosts
  become: true
  roles:
    # https://github.com/c0sco/ansible-modules-bitwarden
    - ansible-modules-bitwarden
    - role: ssh_key
      tags: ssh_key
    - role: initial_bringup
      tags: initial

- hosts: hosts
  vars_files:
    - variables/default.yaml
  roles:
    - role: copy_configuration
      tags: configure
    - role: spin_containers
      tags: run
