id: 530E50AB-68B2-4F1E-81A9-AF851EF869AA
alias: Soggiorno Buzzer
trigger:
  - platform: mqtt
    topic: home/buzzer
    payload: 'on'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.soggiorno_speaker
      media_content_type: sound
      media_content_id: amzn_sfx_doorbell_chime_01