id: E682504C-3B8B-4071-8DEB-9DA8414AD2AB
alias: Soggiorno Cinema Reset
trigger:
  - platform: state
    entity_id: media_player.soggiorno_tv
    to: 'off'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.soggiorno_cinema
