id: 85A8521A-98FC-4C49-B617-F9C426DCA5AF
alias: Soggiorno Cinema Lights
trigger:
  - platform: state
    entity_id: media_player.soggiorno_tv
condition:
  - condition: state
    entity_id: input_boolean.soggiorno_cinema
    state: 'on'
action:
  - service_template: >
      {% if trigger.to_state.state == "playing" %}
        light.turn_off
      {% else %}
        light.turn_on
      {% endif %}
    data:
      entity_id: light.soggiorno_principale
