id: 908ae950-68bb-4b1a-9150-bdef7448e3d6
alias: Soggiorno Cinema ON
trigger:
  - platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: actionable_notification_soggiorno_cinema
      event_response_type: ResponseYes
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.soggiorno_cinema
