id: 12b9b5f6-9125-4a0d-8df2-2db069f1eb81
alias: Soggiorno Media Playing TTS
trigger:
  - platform: state
    entity_id: media_player.soggiorno_tv
    to: 'playing'
condition:
    # Only if using video apps 
  - condition: template
    value_template: >
      {{ trigger.to_state.attributes.app_name in ["Prime Video", "Netflix", "Disney+"] }}

    # And if media is long enough to be considered a movie
  - condition: template
    value_template: >
      {{ trigger.to_state.attributes.media_duration >= 60*45 }}

    # And if cinema mode is not already on
  - condition: state
    entity_id: input_boolean.soggiorno_cinema
    state: 'off'
action:
  - service: script.activate_alexa_actionable_notification
    data_template:
      text: >
        {{
          [
            "Hey! Sembrerebbe ci sia un film in televisione. Spengo le luci?",
            "Bel film, attivo la modalità cinema?",
            "Ora del film. Accendo la modalità cinema?"
          ] | random
        }}
      event_id: actionable_notification_soggiorno_cinema
      alexa_device: media_player.soggiorno_speaker
