---
# Send a notification if there's not going to be water at night.
#
id: 2144017E-820B-497D-B5E6-D1989C39B6CA
alias: Casa Notifica Acqua
trigger:
  - platform: state
    entity_id: binary_sensor.casa_presenza_acqua
    from: 'on'
    to: 'off'
  - platform: time
    at: '13:30:00'
condition:
  - condition: state
    entity_id: binary_sensor.casa_presenza_acqua
    state: 'off'
action:
  - service: script.sistema_text_and_announce
    data_template:
      message: "Potrebbero esserci interruzioni sul servizio idrico"
