---
# Manage lights outside.
#
id: 93473694-53E8-43C2-9259-39F32D177C26
alias: Cortile Luci
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  - platform: state
    entity_id: group.areas_cortile
    to: 'on'
    for:
      minutes: 15
  - platform: state
    entity_id: light.cortile_frontale
  - platform: time
    at: '23:00:00'
action:
  - choose:
      # Lights off but it's evening or bedtime
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: 'below_horizon'
          - condition: time
            before: '23:00:00'
        sequence:
            - service: light.turn_on
              entity_id:
                - light.cortile_frontale

      # Cortile frontale is on and changed rapidly
      - conditions:
          - condition: state
            entity_id: light.cortile_frontale
            state: 'on'
          - condition: template
            value_template: "{{ as_timestamp(now()) - as_timestamp(trigger.from_state.last_changed) <= 0.25 }}"
        sequence:
          - service: light.turn_on
            entity_id:
              - light.cortile_balcone
      - conditions:
          - condition: state
            entity_id: light.cortile_frontale
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            entity_id: group.areas_cortile
    default:
      - service: homeassistant.turn_off
        entity_id: group.areas_cortile
