id: 713ACE4E-8D99-45D1-A1AA-288892BA6513
alias: Cortile Spegnimento Luci Balcone
trigger:
  - platform: state
    entity_id: light.cortile_frontale
    to: 'off'
action:
  - service: light.turn_off
    entity_id: light.cortile_balcone
