id: 713ACE4E-8D99-45D1-A1AA-288892BA6516
alias: Cortile Spegnimento Luci
trigger:
  - platform: state
    entity_id: light.cortile_frontale
    to: 'off'
action:
  - service: homeassistant.turn_off
    entity_id: group.areas_cortile

