id: 0d6718e9-4f62-4468-aa7c-b6add5cc2ba9
alias: Cucina Accensione Luci Scolapiatti
trigger:
  - platform: state
    entity_id: input_select.sistema_stato_del_giorno
  - platform: time
    at: '19:00:00'
  - platform: state
    entity_id: light.cucina_scolapiatti
    to: 'on'
    for:
      hours: 2
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >
          {{ states("input_select.sistema_stato_del_giorno") in ["Mattina"] }}
      - condition: template
        value_template: >
          {{ trigger.platform == "time" }}
      - condition: template
        value_template: >
          {{ trigger.from_state.entity_id == "light.cucina_scolapiatti" }}
      - condition: and
        conditions:
          - condition: template
            value_template: >
              {{ states("input_select.sistema_stato_del_giorno") in ["Pranzo"] }}
          - condition: template
            value_template: >
              {{ states("weather.home") not in ["sunny", "partlycloudy"] }}
action:
  - service_template: >
      {% if trigger.from_state.entity_id == "light.cucina_scolapiatti" %}
        light.turn_off
      {% else %}
        light.turn_on
      {% endif %}
    entity_id: light.cucina_scolapiatti
