---
# Turn on cup heater for the morning.
#
id: 3D666750-268D-4C09-ADB0-75EDC86A5898
alias: Cucina Scaldatazze
trigger:
  - platform: time
    at: '04:30:00'
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: input_select.sistema_stato_del_giorno
  - platform: state
    entity_id: group.family
  - platform: state
    entity_id: group.family
    to: 'not_home'
    for:
      hours: 1
condition:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: >
                  {{ states("input_select.sistema_stato_del_giorno") not in ["Letto", "Notte"] }}
              - condition: template
                value_template: >
                  {{ trigger.platform == "time" }}
          - condition: state
            entity_id: group.family
            state: 'home'
        sequence:
          - service: switch.turn_on
            entity_id: switch.cucina_scaldatazze
    default:
      - service: switch.turn_off
        entity_id: switch.cucina_scaldatazze
